### ISSUE TITLE
Counting the reach of presentations

### ISSUE THREAD

**Issue by kcorrick** [theodi/presentations#12]
Can we add Google Analytics to this area of our GitHub pages so that we can count the reach and how many people are viewing them?

**Comment by davetaz** [comment]
Probably best to include it in the default.html and odi.html layouts. Both are required to cover all presentations.

**Comment by Floppy** [comment]
- [x] create tracker code
- [x] add tracker code to shared layout
- [x] add tracker code to presentations not using shared layouts
